# Generated by Django 6.0.7 on 2026-09-11 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(choices=[('pairwise', 'Pairwise comparisons'), ('ranking', 'Ranking of several movies')], max_length=20)),
                ('consent_given', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('shown_movie_indices', models.JSONField()),
                ('answer_movie_indices', models.JSONField(blank=True, null=True)),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('study_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='project4.studysession')),
            ],
            options={
                'ordering': ['study_session', 'position'],
            },
        ),
    ]
